name: "Dependency Review"
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  is_repo_public:
    runs-on: ubuntu-latest
    steps:
      - name: Check if repo is public
        run: |
          response=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" ${{ github.repository }} | jq -r '.visibility')
          if [ "$response" != "public" ]; then
            echo "Repository is not public. Stopping workflow."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-review:
    needs: is_repo_public
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
      - name: "Dependency Review"
        uses: actions/dependency-review-action@2ce029c676cacb6112c47192ee072c7f783330c5
        with:
          comment-summary-in-pr: always
